export const stadiumNames: Record<string, string> = {
  "India": "Narendra Modi Stadium",
  "Australia": "Melbourne Cricket Ground",
  "England": "Lord's Cricket Ground",
  "Pakistan": "Gaddafi Stadium",
  "New Zealand": "Eden Park",
  "South Africa": "Newlands Cricket Ground",
  "Sri Lanka": "R Premadasa Stadium",
  "West Indies": "Kensington Oval",
  "Chennai Super Kings": "M. A. Chidambaram Stadium",
  "Mumbai Indians": "Wankhede Stadium",
  "Royal Challengers Bengaluru": "M. Chinnaswamy Stadium",
  "Kolkata Knight Riders": "Eden Gardens",
  "Gujarat Titans": "Narendra Modi Stadium",
  "Rajasthan Royals": "Sawai Mansingh Stadium",
  "Sunrisers Hyderabad": "Rajiv Gandhi International Stadium",
  "Punjab Kings": "IS Bindra Stadium",
  "Delhi Capitals": "Arun Jaitley Stadium",
  "Lucknow Super Giants": "BRSABV Ekana Stadium",
};

export const internationalCricketData = [
  {
    id:1,
    name: "India",
    countryCode: "ind",
    logo: "/india_logo.jpg",
    players: [
  {
    id: 1,
    name: "Rohit Sharma",
    role: "Batter",
    overall: 93,
    batting: 95,
    bowling: 18,
  },
  {
    id: 2,
    name: "Virat Kohli",
    role: "Batter",
    overall: 94,
    batting: 97,
    bowling: 20,
  },
  {
    id: 3,
    name: "Shubman Gill",
    role: "Batter",
    overall: 90,
    batting: 94,
    bowling: 22,
  },
  {
    id: 4,
    name: "Yashasvi Jaiswal",
    role: "Batter",
    overall: 89,
    batting: 93,
    bowling: 15,
  },
  {
    id: 5,
    name: "Suryakumar Yadav",
    role: "Batter",
    overall: 92,
    batting: 96,
    bowling: 20,
  },
  {
    id: 6,
    name: "Tilak Varma",
    role: "Batter",
    overall: 87,
    batting: 90,
    bowling: 25,
  },
  {
    id: 7,
    name: "Rinku Singh",
    role: "Batter",
    overall: 88,
    batting: 92,
    bowling: 15,
  },
  {
    id: 8,
    name: "KL Rahul",
    role: "WK",
    overall: 90,
    batting: 93,
    bowling: 12,
  },
  {
    id: 9,
    name: "Rishabh Pant",
    role: "WK",
    overall: 91,
    batting: 94,
    bowling: 12,
  },
  {
    id: 10,
    name: "Hardik Pandya",
    role: "AR",
    overall: 91,
    batting: 90,
    bowling: 88,
  },
  {
    id: 11,
    name: "Ravindra Jadeja",
    role: "AR",
    overall: 92,
    batting: 85,
    bowling: 93,
  },
  {
    id: 12,
    name: "Axar Patel",
    role: "AR",
    overall: 86,
    batting: 78,
    bowling: 89,
  },
  {
    id: 13,
    name: "Washington Sundar",
    role: "AR",
    overall: 84,
    batting: 75,
    bowling: 88,
  },
  {
    id: 14,
    name: "Jasprit Bumrah",
    role: "Bowler",
    overall: 95,
    batting: 30,
    bowling: 98,
  },
  {
    id: 15,
    name: "Mohammed Siraj",
    role: "Bowler",
    overall: 88,
    batting: 25,
    bowling: 92,
  },
  {
    id: 16,
    name: "Kuldeep Yadav",
    role: "Bowler",
    overall: 89,
    batting: 35,
    bowling: 94,
  },
  {
    id: 17,
    name: "Arshdeep Singh",
    role: "Bowler",
    overall: 86,
    batting: 28,
    bowling: 90,
  },
  {
    id: 18,
    name: "Mohammed Shami",
    role: "Bowler",
    overall: 90,
    batting: 32,
    bowling: 94,
  }
]
  },
  {
    id:2,
    name: "Australia",
    countryCode: "aus",
    logo :"/australia_logo.jpg",
    players: [
  {
    id: 1,
    name: "David Warner",
    role: "Batter",
    overall: 90,
    batting: 93,
    bowling: 15,
  },
  {
    id: 2,
    name: "Steve Smith",
    role: "Batter",
    overall: 92,
    batting: 95,
    bowling: 25,
  },
  {
    id: 3,
    name: "Travis Head",
    role: "Batter",
    overall: 91,
    batting: 94,
    bowling: 30,
  },
  {
    id: 4,
    name: "Marnus Labuschagne",
    role: "Batter",
    overall: 89,
    batting: 92,
    bowling: 30,
  },
  {
    id: 5,
    name: "Glenn Maxwell",
    role: "AR",
    overall: 92,
    batting: 95,
    bowling: 80,
  },
  {
    id: 6,
    name: "Mitchell Marsh",
    role: "AR",
    overall: 90,
    batting: 92,
    bowling: 78,
  },
  {
    id: 7,
    name: "Cameron Green",
    role: "AR",
    overall: 87,
    batting: 85,
    bowling: 84,
  },
  {
    id: 8,
    name: "Marcus Stoinis",
    role: "AR",
    overall: 88,
    batting: 89,
    bowling: 82,
  },
  {
    id: 9,
    name: "Alex Carey",
    role: "WK",
    overall: 84,
    batting: 86,
    bowling: 10,
  },
  {
    id: 10,
    name: "Josh Inglis",
    role: "WK",
    overall: 85,
    batting: 88,
    bowling: 12,
  },
  {
    id: 11,
    name: "Pat Cummins",
    role: "Bowler",
    overall: 91,
    batting: 60,
    bowling: 94,
  },
  {
    id: 12,
    name: "Mitchell Starc",
    role: "Bowler",
    overall: 92,
    batting: 55,
    bowling: 96,
  },
  {
    id: 13,
    name: "Josh Hazlewood",
    role: "Bowler",
    overall: 90,
    batting: 40,
    bowling: 95,
  },
  {
    id: 14,
    name: "Adam Zampa",
    role: "Bowler",
    overall: 88,
    batting: 30,
    bowling: 92,
  },
  {
    id: 15,
    name: "Nathan Lyon",
    role: "Bowler",
    overall: 87,
    batting: 35,
    bowling: 93,
  },
  {
    id: 16,
    name: "Sean Abbott",
    role: "AR",
    overall: 82,
    batting: 78,
    bowling: 85,
  },
  {
    id: 17,
    name: "Jake Fraser McGurk",
    role: "Batter",
    overall: 84,
    batting: 88,
    bowling: 15,
  },
  {
    id: 18,
    name: "Matthew Short",
    role: "AR",
    overall: 83,
    batting: 86,
    bowling: 75,
  },
]
  },

  {
    id:3,
    name: "England",
    countryCode: "Eng",
    logo:"/england_logo.jpg",
    players: [
  {
    id: 1,
    name: "Jos Buttler",
    role: "WK",
    overall: 93,
    batting: 96,
    bowling: 12,
  },
  {
    id: 2,
    name: "Jonny Bairstow",
    role: "Batter",
    overall: 90,
    batting: 93,
    bowling: 18,
  },
  {
    id: 3,
    name: "Joe Root",
    role: "Batter",
    overall: 94,
    batting: 97,
    bowling: 40,
  },
  {
    id: 4,
    name: "Harry Brook",
    role: "Batter",
    overall: 88,
    batting: 91,
    bowling: 20,
  },
  {
    id: 5,
    name: "Ben Stokes",
    role: "AR",
    overall: 95,
    batting: 94,
    bowling: 90,
  },
  {
    id: 6,
    name: "Sam Curran",
    role: "AR",
    overall: 89,
    batting: 88,
    bowling: 86,
  },
  {
    id: 7,
    name: "Moeen Ali",
    role: "AR",
    overall: 87,
    batting: 85,
    bowling: 88,
  },
  {
    id: 8,
    name: "Chris Woakes",
    role: "AR",
    overall: 88,
    batting: 75,
    bowling: 92,
  },
  {
    id: 9,
    name: "Phil Salt",
    role: "WK",
    overall: 86,
    batting: 90,
    bowling: 12,
  },
  {
    id: 10,
    name: "Mark Wood",
    role: "Bowler",
    overall: 89,
    batting: 35,
    bowling: 94,
  },
  {
    id: 11,
    name: "Jofra Archer",
    role: "Bowler",
    overall: 90,
    batting: 40,
    bowling: 95,
  },
  {
    id: 12,
    name: "Adil Rashid",
    role: "Bowler",
    overall: 88,
    batting: 28,
    bowling: 93,
  },
  {
    id: 13,
    name: "Reece Topley",
    role: "Bowler",
    overall: 84,
    batting: 25,
    bowling: 90,
  },
  {
    id: 14,
    name: "Gus Atkinson",
    role: "Bowler",
    overall: 83,
    batting: 30,
    bowling: 88,
  },
  {
    id: 15,
    name: "Liam Livingstone",
    role: "AR",
    overall: 90,
    batting: 92,
    bowling: 78,
  },
  {
    id: 16,
    name: "Dawid Malan",
    role: "Batter",
    overall: 87,
    batting: 90,
    bowling: 15,
  },
  {
    id: 17,
    name: "Tom Hartley",
    role: "Bowler",
    overall: 80,
    batting: 28,
    bowling: 85,
  },
  {
    id: 18,
    name: "Will Jacks",
    role: "AR",
    overall: 85,
    batting: 88,
    bowling: 70,
  },
]
  },

  {
    id:4,
    name: "Pakistan",
    countryCode: "pak",
    logo:"/pakistan_logo.jpg",
    players: [
  {
    id: 1,
    name: "Babar Azam",
    role: "Batter",
    overall: 94,
    batting: 97,
    bowling: 20,
  },
  {
    id: 2,
    name: "Mohammad Rizwan",
    role: "WK",
    overall: 92,
    batting: 95,
    bowling: 15,
  },
  {
    id: 3,
    name: "Fakhar Zaman",
    role: "Batter",
    overall: 87,
    batting: 90,
    bowling: 18,
  },
  {
    id: 4,
    name: "Saim Ayub",
    role: "Batter",
    overall: 82,
    batting: 85,
    bowling: 25,
  },
  {
    id: 5,
    name: "Iftikhar Ahmed",
    role: "AR",
    overall: 84,
    batting: 86,
    bowling: 70,
  },
  {
    id: 6,
    name: "Shadab Khan",
    role: "AR",
    overall: 88,
    batting: 80,
    bowling: 91,
  },
  {
    id: 7,
    name: "Imad Wasim",
    role: "AR",
    overall: 85,
    batting: 78,
    bowling: 88,
  },
  {
    id: 8,
    name: "Mohammad Nawaz",
    role: "AR",
    overall: 83,
    batting: 75,
    bowling: 87,
  },
  {
    id: 9,
    name: "Azam Khan",
    role: "WK",
    overall: 80,
    batting: 85,
    bowling: 10,
  },
  {
    id: 10,
    name: "Shaheen Afridi",
    role: "Bowler",
    overall: 93,
    batting: 45,
    bowling: 96,
  },
  {
    id: 11,
    name: "Haris Rauf",
    role: "Bowler",
    overall: 89,
    batting: 30,
    bowling: 94,
  },
  {
    id: 12,
    name: "Naseem Shah",
    role: "Bowler",
    overall: 88,
    batting: 35,
    bowling: 93,
  },
  {
    id: 13,
    name: "Hasan Ali",
    role: "Bowler",
    overall: 84,
    batting: 40,
    bowling: 90,
  },
  {
    id: 14,
    name: "Usama Mir",
    role: "Bowler",
    overall: 82,
    batting: 30,
    bowling: 88,
  },
  {
    id: 15,
    name: "Abrar Ahmed",
    role: "Bowler",
    overall: 83,
    batting: 25,
    bowling: 89,
  },
  {
    id: 16,
    name: "Salman Agha",
    role: "AR",
    overall: 84,
    batting: 82,
    bowling: 80,
  },
  {
    id: 17,
    name: "Khushdil Shah",
    role: "AR",
    overall: 81,
    batting: 83,
    bowling: 70,
  },
  {
    id: 18,
    name: "Zaman Khan",
    role: "Bowler",
    overall: 82,
    batting: 28,
    bowling: 88,
  },
]
  },

  {
    id:5,
    name: "New Zealand",
    countryCode: "NZ",
    logo:"/new_zealand_logo.jpg",
    players: [
  {
    id: 1,
    name: "Kane Williamson",
    role: "Batter",
    overall: 94,
    batting: 97,
    bowling: 35,
  },
  {
    id: 2,
    name: "Devon Conway",
    role: "WK",
    overall: 90,
    batting: 93,
    bowling: 10,
  },
  {
    id: 3,
    name: "Finn Allen",
    role: "Batter",
    overall: 85,
    batting: 89,
    bowling: 15,
  },
  {
    id: 4,
    name: "Rachin Ravindra",
    role: "AR",
    overall: 89,
    batting: 90,
    bowling: 84,
  },
  {
    id: 5,
    name: "Daryl Mitchell",
    role: "AR",
    overall: 90,
    batting: 91,
    bowling: 82,
  },
  {
    id: 6,
    name: "Glenn Phillips",
    role: "AR",
    overall: 88,
    batting: 90,
    bowling: 75,
  },
  {
    id: 7,
    name: "Mitchell Santner",
    role: "AR",
    overall: 87,
    batting: 78,
    bowling: 90,
  },
  {
    id: 8,
    name: "Tom Latham",
    role: "WK",
    overall: 85,
    batting: 87,
    bowling: 10,
  },
  {
    id: 9,
    name: "Trent Boult",
    role: "Bowler",
    overall: 92,
    batting: 40,
    bowling: 95,
  },
  {
    id: 10,
    name: "Tim Southee",
    role: "Bowler",
    overall: 89,
    batting: 50,
    bowling: 93,
  },
  {
    id: 11,
    name: "Lockie Ferguson",
    role: "Bowler",
    overall: 88,
    batting: 30,
    bowling: 94,
  },
  {
    id: 12,
    name: "Matt Henry",
    role: "Bowler",
    overall: 87,
    batting: 35,
    bowling: 92,
  },
  {
    id: 13,
    name: "Ish Sodhi",
    role: "Bowler",
    overall: 85,
    batting: 25,
    bowling: 90,
  },
  {
    id: 14,
    name: "Will Young",
    role: "Batter",
    overall: 83,
    batting: 86,
    bowling: 15,
  },
  {
    id: 15,
    name: "Mark Chapman",
    role: "Batter",
    overall: 84,
    batting: 88,
    bowling: 30,
  },
  {
    id: 16,
    name: "Jimmy Neesham",
    role: "AR",
    overall: 86,
    batting: 87,
    bowling: 80,
  },
  {
    id: 17,
    name: "Michael Bracewell",
    role: "AR",
    overall: 85,
    batting: 86,
    bowling: 82,
  },
  {
    id: 18,
    name: "Ben Sears",
    role: "Bowler",
    overall: 82,
    batting: 28,
    bowling: 88,
  },
]
  },

  {
    id:6,
    name: "South Africa",
    countryCode: "SA",
    logo:"/south_africa_logo.jpg",
    players: [
  {
    id: 1,
    name: "Quinton de Kock",
    role: "WK",
    overall: 91,
    batting: 94,
    bowling: 10,
  },
  {
    id: 2,
    name: "Temba Bavuma",
    role: "Batter",
    overall: 85,
    batting: 88,
    bowling: 15,
  },
  {
    id: 3,
    name: "Reeza Hendricks",
    role: "Batter",
    overall: 84,
    batting: 88,
    bowling: 12,
  },
  {
    id: 4,
    name: "Aiden Markram",
    role: "AR",
    overall: 90,
    batting: 92,
    bowling: 80,
  },
  {
    id: 5,
    name: "Heinrich Klaasen",
    role: "WK",
    overall: 90,
    batting: 94,
    bowling: 12,
  },
  {
    id: 6,
    name: "David Miller",
    role: "Batter",
    overall: 89,
    batting: 92,
    bowling: 18,
  },
  {
    id: 7,
    name: "Marco Jansen",
    role: "AR",
    overall: 88,
    batting: 75,
    bowling: 92,
  },
  {
    id: 8,
    name: "Andile Phehlukwayo",
    role: "AR",
    overall: 82,
    batting: 80,
    bowling: 85,
  },
  {
    id: 9,
    name: "Kagiso Rabada",
    role: "Bowler",
    overall: 92,
    batting: 45,
    bowling: 95,
  },
  {
    id: 10,
    name: "Anrich Nortje",
    role: "Bowler",
    overall: 89,
    batting: 35,
    bowling: 94,
  },
  {
    id: 11,
    name: "Lungi Ngidi",
    role: "Bowler",
    overall: 86,
    batting: 40,
    bowling: 91,
  },
  {
    id: 12,
    name: "Keshav Maharaj",
    role: "Bowler",
    overall: 87,
    batting: 40,
    bowling: 91,
  },
  {
    id: 13,
    name: "Tabraiz Shamsi",
    role: "Bowler",
    overall: 86,
    batting: 25,
    bowling: 92,
  },
  {
    id: 14,
    name: "Gerald Coetzee",
    role: "Bowler",
    overall: 88,
    batting: 38,
    bowling: 93,
  },
  {
    id: 15,
    name: "Ryan Rickelton",
    role: "WK",
    overall: 83,
    batting: 86,
    bowling: 10,
  },
  {
    id: 16,
    name: "Rassie van der Dussen",
    role: "Batter",
    overall: 88,
    batting: 91,
    bowling: 15,
  },
  {
    id: 17,
    name: "Tristan Stubbs",
    role: "AR",
    overall: 86,
    batting: 88,
    bowling: 65,
  },
  {
    id: 18,
    name: "Bjorn Fortuin",
    role: "Bowler",
    overall: 82,
    batting: 28,
    bowling: 88,
  },
]
  },

  {
    id:7,
    name: "Sri Lanka",
    countryCode: "SL",
    logo:"/sri_lanka_logo.jpg",
    players: [
  {
    id: 1,
    name: "Kusal Mendis",
    role: "WK",
    overall: 88,
    batting: 91,
    bowling: 12,
  },
  {
    id: 2,
    name: "Pathum Nissanka",
    role: "Batter",
    overall: 87,
    batting: 90,
    bowling: 15,
  },
  {
    id: 3,
    name: "Avishka Fernando",
    role: "Batter",
    overall: 83,
    batting: 87,
    bowling: 12,
  },
  {
    id: 4,
    name: "Charith Asalanka",
    role: "Batter",
    overall: 86,
    batting: 89,
    bowling: 30,
  },
  {
    id: 5,
    name: "Dhananjaya de Silva",
    role: "AR",
    overall: 88,
    batting: 87,
    bowling: 88,
  },
  {
    id: 6,
    name: "Dasun Shanaka",
    role: "AR",
    overall: 85,
    batting: 86,
    bowling: 80,
  },
  {
    id: 7,
    name: "Wanindu Hasaranga",
    role: "AR",
    overall: 92,
    batting: 85,
    bowling: 96,
  },
  {
    id: 8,
    name: "Angelo Mathews",
    role: "AR",
    overall: 86,
    batting: 85,
    bowling: 82,
  },
  {
    id: 9,
    name: "Maheesh Theekshana",
    role: "Bowler",
    overall: 88,
    batting: 35,
    bowling: 93,
  },
  {
    id: 10,
    name: "Matheesha Pathirana",
    role: "Bowler",
    overall: 89,
    batting: 28,
    bowling: 95,
  },
  {
    id: 11,
    name: "Dilshan Madushanka",
    role: "Bowler",
    overall: 87,
    batting: 30,
    bowling: 92,
  },
  {
    id: 12,
    name: "Dushmantha Chameera",
    role: "Bowler",
    overall: 85,
    batting: 35,
    bowling: 90,
  },
  {
    id: 13,
    name: "Jeffrey Vandersay",
    role: "Bowler",
    overall: 82,
    batting: 25,
    bowling: 88,
  },
  {
    id: 14,
    name: "Sadeera Samarawickrama",
    role: "WK",
    overall: 84,
    batting: 87,
    bowling: 10,
  },
  {
    id: 15,
    name: "Kamindu Mendis",
    role: "AR",
    overall: 85,
    batting: 86,
    bowling: 78,
  },
  {
    id: 16,
    name: "Nuwan Thushara",
    role: "Bowler",
    overall: 83,
    batting: 28,
    bowling: 89,
  },
  {
    id: 17,
    name: "Chamika Karunaratne",
    role: "AR",
    overall: 82,
    batting: 80,
    bowling: 84,
  },
  {
    id: 18,
    name: "Bhanuka Rajapaksa",
    role: "Batter",
    overall: 84,
    batting: 88,
    bowling: 15,
  },
]
  },

  {
    id:8,
    name: "West Indies",
    countryCode: "WI",
    logo:"/west_indies_logo.jpg",
    players: [
  {
    id: 1,
    name: "Nicholas Pooran",
    role: "WK",
    overall: 91,
    batting: 95,
    bowling: 12,
  },
  {
    id: 2,
    name: "Shai Hope",
    role: "WK",
    overall: 89,
    batting: 92,
    bowling: 10,
  },
  {
    id: 3,
    name: "Brandon King",
    role: "Batter",
    overall: 85,
    batting: 88,
    bowling: 15,
  },
  {
    id: 4,
    name: "Shimron Hetmyer",
    role: "Batter",
    overall: 88,
    batting: 92,
    bowling: 18,
  },
  {
    id: 5,
    name: "Rovman Powell",
    role: "AR",
    overall: 88,
    batting: 90,
    bowling: 70,
  },
  {
    id: 6,
    name: "Kyle Mayers",
    role: "AR",
    overall: 87,
    batting: 89,
    bowling: 82,
  },
  {
    id: 7,
    name: "Andre Russell",
    role: "AR",
    overall: 92,
    batting: 94,
    bowling: 90,
  },
  {
    id: 8,
    name: "Jason Holder",
    role: "AR",
    overall: 90,
    batting: 80,
    bowling: 93,
  },
  {
    id: 9,
    name: "Akeal Hosein",
    role: "Bowler",
    overall: 87,
    batting: 35,
    bowling: 92,
  },
  {
    id: 10,
    name: "Alzarri Joseph",
    role: "Bowler",
    overall: 89,
    batting: 40,
    bowling: 94,
  },
  {
    id: 11,
    name: "Gudakesh Motie",
    role: "Bowler",
    overall: 84,
    batting: 30,
    bowling: 90,
  },
  {
    id: 12,
    name: "Obed McCoy",
    role: "Bowler",
    overall: 83,
    batting: 28,
    bowling: 89,
  },
  {
    id: 13,
    name: "Romario Shepherd",
    role: "AR",
    overall: 86,
    batting: 88,
    bowling: 82,
  },
  {
    id: 14,
    name: "Johnson Charles",
    role: "WK",
    overall: 84,
    batting: 87,
    bowling: 10,
  },
  {
    id: 15,
    name: "Evin Lewis",
    role: "Batter",
    overall: 86,
    batting: 90,
    bowling: 15,
  },
  {
    id: 16,
    name: "Keemo Paul",
    role: "AR",
    overall: 82,
    batting: 78,
    bowling: 85,
  },
  {
    id: 17,
    name: "Odean Smith",
    role: "AR",
    overall: 83,
    batting: 84,
    bowling: 80,
  },
  {
    id: 18,
    name: "Shamar Joseph",
    role: "Bowler",
    overall: 88,
    batting: 35,
    bowling: 93,
  },
]
  },
];

export const iplCricketData = [
  {
    id:9,
    name: "Chennai Super Kings",
    countryCode: "CSK",
    logo:"/csk_logo.jpg",
    players: [
  {
    id: 1,
    name: "Ruturaj Gaikwad",
    role: "Batter",
    overall: 90,
    batting: 93,
    bowling: 15,
  },
  {
    id: 2,
    name: "MS Dhoni",
    role: "WK",
    overall: 86,
    batting: 85,
    bowling: 5,
  },
  {
    id: 3,
    name: "Devon Conway",
    role: "WK",
    overall: 89,
    batting: 92,
    bowling: 10,
  },
  {
    id: 4,
    name: "Ajinkya Rahane",
    role: "Batter",
    overall: 84,
    batting: 87,
    bowling: 20,
  },
  {
    id: 5,
    name: "Shivam Dube",
    role: "AR",
    overall: 85,
    batting: 88,
    bowling: 70,
  },
  {
    id: 6,
    name: "Ravindra Jadeja",
    role: "AR",
    overall: 92,
    batting: 85,
    bowling: 93,
  },
  {
    id: 7,
    name: "Moeen Ali",
    role: "AR",
    overall: 88,
    batting: 86,
    bowling: 88,
  },
  {
    id: 8,
    name: "Mitchell Santner",
    role: "AR",
    overall: 86,
    batting: 78,
    bowling: 90,
  },
  {
    id: 9,
    name: "Deepak Chahar",
    role: "Bowler",
    overall: 87,
    batting: 45,
    bowling: 92,
  },
  {
    id: 10,
    name: "Matheesha Pathirana",
    role: "Bowler",
    overall: 90,
    batting: 25,
    bowling: 96,
  },
  {
    id: 11,
    name: "Maheesh Theekshana",
    role: "Bowler",
    overall: 88,
    batting: 30,
    bowling: 93,
  },
  {
    id: 12,
    name: "Tushar Deshpande",
    role: "Bowler",
    overall: 82,
    batting: 30,
    bowling: 88,
  },
  {
    id: 13,
    name: "Shardul Thakur",
    role: "AR",
    overall: 85,
    batting: 75,
    bowling: 87,
  },
  {
    id: 14,
    name: "Sameer Rizvi",
    role: "Batter",
    overall: 78,
    batting: 82,
    bowling: 10,
  },
  {
    id: 15,
    name: "Rajvardhan Hangargekar",
    role: "AR",
    overall: 80,
    batting: 78,
    bowling: 84,
  },
  {
    id: 16,
    name: "Mukesh Choudhary",
    role: "Bowler",
    overall: 79,
    batting: 25,
    bowling: 86,
  },
  {
    id: 17,
    name: "Prashant Solanki",
    role: "Bowler",
    overall: 77,
    batting: 20,
    bowling: 85,
  },
  {
    id: 18,
    name: "Nishant Sindhu",
    role: "AR",
    overall: 78,
    batting: 80,
    bowling: 75,
  },
]
  },
  {
    id:10,
    name: "Mumbai Indians",
    countryCode: "MI",
    logo:"/mi_logo.jpg",
    players: [
  {
    id: 1,
    name: "Rohit Sharma",
    role: "Batter",
    overall: 93,
    batting: 95,
    bowling: 18,
  },
  {
    id: 2,
    name: "Ishan Kishan",
    role: "WK",
    overall: 85,
    batting: 88,
    bowling: 10,
  },
  {
    id: 3,
    name: "Suryakumar Yadav",
    role: "Batter",
    overall: 94,
    batting: 97,
    bowling: 20,
  },
  {
    id: 4,
    name: "Tilak Varma",
    role: "Batter",
    overall: 88,
    batting: 91,
    bowling: 25,
  },
  {
    id: 5,
    name: "Hardik Pandya",
    role: "AR",
    overall: 92,
    batting: 90,
    bowling: 89,
  },
  {
    id: 6,
    name: "Tim David",
    role: "Batter",
    overall: 87,
    batting: 90,
    bowling: 15,
  },
  {
    id: 7,
    name: "Romario Shepherd",
    role: "AR",
    overall: 85,
    batting: 86,
    bowling: 82,
  },
  {
    id: 8,
    name: "Mohammad Nabi",
    role: "AR",
    overall: 86,
    batting: 80,
    bowling: 88,
  },
  {
    id: 9,
    name: "Jasprit Bumrah",
    role: "Bowler",
    overall: 96,
    batting: 30,
    bowling: 99,
  },
  {
    id: 10,
    name: "Gerald Coetzee",
    role: "Bowler",
    overall: 88,
    batting: 35,
    bowling: 93,
  },
  {
    id: 11,
    name: "Akash Madhwal",
    role: "Bowler",
    overall: 83,
    batting: 25,
    bowling: 89,
  },
  {
    id: 12,
    name: "Piyush Chawla",
    role: "Bowler",
    overall: 82,
    batting: 40,
    bowling: 88,
  },
  {
    id: 13,
    name: "Shreyas Gopal",
    role: "AR",
    overall: 80,
    batting: 70,
    bowling: 85,
  },
  {
    id: 14,
    name: "Nehal Wadhera",
    role: "Batter",
    overall: 82,
    batting: 86,
    bowling: 15,
  },
  {
    id: 15,
    name: "Naman Dhir",
    role: "AR",
    overall: 78,
    batting: 80,
    bowling: 75,
  },
  {
    id: 16,
    name: "Arjun Tendulkar",
    role: "AR",
    overall: 76,
    batting: 65,
    bowling: 80,
  },
  {
    id: 17,
    name: "Luke Wood",
    role: "Bowler",
    overall: 81,
    batting: 30,
    bowling: 88,
  },
  {
    id: 18,
    name: "Dewald Brevis",
    role: "Batter",
    overall: 84,
    batting: 89,
    bowling: 20,
  },
]
  },
  {
    id:11,
    name: "Royal Challengers Bengaluru",
    countryCode: "RCB",
    logo:"/rcb_logo.jpg",
    players: [
  {
    id: 1,
    name: "Virat Kohli",
    role: "Batter",
    overall: 95,
    batting: 98,
    bowling: 20,
  },
  {
    id: 2,
    name: "Faf du Plessis",
    role: "Batter",
    overall: 91,
    batting: 94,
    bowling: 15,
  },
  {
    id: 3,
    name: "Rajat Patidar",
    role: "Batter",
    overall: 86,
    batting: 89,
    bowling: 10,
  },
  {
    id: 4,
    name: "Glenn Maxwell",
    role: "AR",
    overall: 92,
    batting: 95,
    bowling: 80,
  },
  {
    id: 5,
    name: "Cameron Green",
    role: "AR",
    overall: 88,
    batting: 86,
    bowling: 85,
  },
  {
    id: 6,
    name: "Dinesh Karthik",
    role: "WK",
    overall: 84,
    batting: 87,
    bowling: 5,
  },
  {
    id: 7,
    name: "Mahipal Lomror",
    role: "AR",
    overall: 81,
    batting: 83,
    bowling: 70,
  },
  {
    id: 8,
    name: "Anuj Rawat",
    role: "WK",
    overall: 79,
    batting: 82,
    bowling: 5,
  },
  {
    id: 9,
    name: "Mohammed Siraj",
    role: "Bowler",
    overall: 89,
    batting: 30,
    bowling: 93,
  },
  {
    id: 10,
    name: "Reece Topley",
    role: "Bowler",
    overall: 85,
    batting: 25,
    bowling: 91,
  },
  {
    id: 11,
    name: "Lockie Ferguson",
    role: "Bowler",
    overall: 88,
    batting: 30,
    bowling: 94,
  },
  {
    id: 12,
    name: "Karn Sharma",
    role: "Bowler",
    overall: 80,
    batting: 40,
    bowling: 86,
  },
  {
    id: 13,
    name: "Mayank Dagar",
    role: "AR",
    overall: 78,
    batting: 70,
    bowling: 85,
  },
  {
    id: 14,
    name: "Vyshak Vijaykumar",
    role: "Bowler",
    overall: 79,
    batting: 25,
    bowling: 87,
  },
  {
    id: 15,
    name: "Suyash Prabhudessai",
    role: "Batter",
    overall: 80,
    batting: 84,
    bowling: 20,
  },
  {
    id: 16,
    name: "Himanshu Sharma",
    role: "Bowler",
    overall: 76,
    batting: 20,
    bowling: 83,
  },
  {
    id: 17,
    name: "Tom Curran",
    role: "AR",
    overall: 84,
    batting: 80,
    bowling: 88,
  },
  {
    id: 18,
    name: "Will Jacks",
    role: "AR",
    overall: 87,
    batting: 90,
    bowling: 75,
  },
]
  },
  {
    id:12,
    name: "Kolkata Knight Riders",
    countryCode: "KKR",
    logo:"/kkr_logo.jpg",
    players: [
  {
    id: 1,
    name: "Shreyas Iyer",
    role: "Batter",
    overall: 89,
    batting: 92,
    bowling: 20,
  },
  {
    id: 2,
    name: "Rinku Singh",
    role: "Batter",
    overall: 90,
    batting: 94,
    bowling: 15,
  },
  {
    id: 3,
    name: "Nitish Rana",
    role: "AR",
    overall: 86,
    batting: 88,
    bowling: 65,
  },
  {
    id: 4,
    name: "Rahmanullah Gurbaz",
    role: "WK",
    overall: 85,
    batting: 89,
    bowling: 5,
  },
  {
    id: 5,
    name: "Andre Russell",
    role: "AR",
    overall: 94,
    batting: 95,
    bowling: 92,
  },
  {
    id: 6,
    name: "Sunil Narine",
    role: "AR",
    overall: 92,
    batting: 82,
    bowling: 96,
  },
  {
    id: 7,
    name: "Venkatesh Iyer",
    role: "AR",
    overall: 88,
    batting: 90,
    bowling: 75,
  },
  {
    id: 8,
    name: "Jason Roy",
    role: "Batter",
    overall: 86,
    batting: 90,
    bowling: 10,
  },
  {
    id: 9,
    name: "Varun Chakravarthy",
    role: "Bowler",
    overall: 89,
    batting: 20,
    bowling: 94,
  },
  {
    id: 10,
    name: "Mitchell Starc",
    role: "Bowler",
    overall: 93,
    batting: 50,
    bowling: 97,
  },
  {
    id: 11,
    name: "Harshit Rana",
    role: "Bowler",
    overall: 82,
    batting: 30,
    bowling: 88,
  },
  {
    id: 12,
    name: "Suyash Sharma",
    role: "Bowler",
    overall: 83,
    batting: 25,
    bowling: 90,
  },
  {
    id: 13,
    name: "Chetan Sakariya",
    role: "Bowler",
    overall: 81,
    batting: 35,
    bowling: 87,
  },
  {
    id: 14,
    name: "Anukul Roy",
    role: "AR",
    overall: 79,
    batting: 75,
    bowling: 82,
  },
  {
    id: 15,
    name: "Vaibhav Arora",
    role: "Bowler",
    overall: 80,
    batting: 28,
    bowling: 86,
  },
  {
    id: 16,
    name: "Angkrish Raghuvanshi",
    role: "Batter",
    overall: 78,
    batting: 82,
    bowling: 10,
  },
  {
    id: 17,
    name: "Manish Pandey",
    role: "Batter",
    overall: 83,
    batting: 86,
    bowling: 15,
  },
  {
    id: 18,
    name: "Sherfane Rutherford",
    role: "AR",
    overall: 84,
    batting: 88,
    bowling: 70,
  },
]
  },
  {
    id:13,
    name: "Gujarat Titans",
    countryCode: "GT",
    logo:"/gt_logo.jpg",
    players: [
  {
    id: 1,
    name: "Shubman Gill",
    role: "Batter",
    overall: 92,
    batting: 95,
    bowling: 20,
  },
  {
    id: 2,
    name: "Wriddhiman Saha",
    role: "WK",
    overall: 82,
    batting: 85,
    bowling: 5,
  },
  {
    id: 3,
    name: "Sai Sudharsan",
    role: "Batter",
    overall: 86,
    batting: 90,
    bowling: 10,
  },
  {
    id: 4,
    name: "David Miller",
    role: "Batter",
    overall: 88,
    batting: 91,
    bowling: 15,
  },
  {
    id: 5,
    name: "Rahul Tewatia",
    role: "AR",
    overall: 86,
    batting: 88,
    bowling: 75,
  },
  {
    id: 6,
    name: "Vijay Shankar",
    role: "AR",
    overall: 83,
    batting: 85,
    bowling: 72,
  },
  {
    id: 7,
    name: "Azmatullah Omarzai",
    role: "AR",
    overall: 84,
    batting: 82,
    bowling: 80,
  },
  {
    id: 8,
    name: "Rashid Khan",
    role: "AR",
    overall: 95,
    batting: 85,
    bowling: 99,
  },
  {
    id: 9,
    name: "Noor Ahmad",
    role: "Bowler",
    overall: 87,
    batting: 25,
    bowling: 93,
  },
  {
    id: 10,
    name: "Mohit Sharma",
    role: "Bowler",
    overall: 85,
    batting: 35,
    bowling: 90,
  },
  {
    id: 11,
    name: "Spencer Johnson",
    role: "Bowler",
    overall: 83,
    batting: 30,
    bowling: 88,
  },
  {
    id: 12,
    name: "Umesh Yadav",
    role: "Bowler",
    overall: 84,
    batting: 40,
    bowling: 89,
  },
  {
    id: 13,
    name: "Kane Williamson",
    role: "Batter",
    overall: 89,
    batting: 92,
    bowling: 20,
  },
  {
    id: 14,
    name: "Abhinav Manohar",
    role: "Batter",
    overall: 80,
    batting: 84,
    bowling: 10,
  },
  {
    id: 15,
    name: "Shahrukh Khan",
    role: "Batter",
    overall: 82,
    batting: 87,
    bowling: 20,
  },
  {
    id: 16,
    name: "Joshua Little",
    role: "Bowler",
    overall: 81,
    batting: 25,
    bowling: 87,
  },
  {
    id: 17,
    name: "Jayant Yadav",
    role: "AR",
    overall: 79,
    batting: 70,
    bowling: 82,
  },
  {
    id: 18,
    name: "Sandeep Warrier",
    role: "Bowler",
    overall: 78,
    batting: 20,
    bowling: 85,
  },
]
  },
  {
    id:14,
    name: "Rajasthan Royals",
    countryCode: "RR",
    logo:"/rr_logo.jpg",
    players: [
  {
    id: 1,
    name: "Sanju Samson",
    role: "WK",
    overall: 91,
    batting: 94,
    bowling: 5,
  },
  {
    id: 2,
    name: "Yashasvi Jaiswal",
    role: "Batter",
    overall: 91,
    batting: 95,
    bowling: 15,
  },
  {
    id: 3,
    name: "Jos Buttler",
    role: "WK",
    overall: 93,
    batting: 96,
    bowling: 10,
  },
  {
    id: 4,
    name: "Riyan Parag",
    role: "AR",
    overall: 86,
    batting: 88,
    bowling: 72,
  },
  {
    id: 5,
    name: "Shimron Hetmyer",
    role: "Batter",
    overall: 88,
    batting: 92,
    bowling: 10,
  },
  {
    id: 6,
    name: "Dhruv Jurel",
    role: "AR",
    overall: 84,
    batting: 87,
    bowling: 5,
  },
  {
    id: 7,
    name: "Ravichandran Ashwin",
    role: "AR",
    overall: 88,
    batting: 80,
    bowling: 92,
  },
  {
    id: 8,
    name: "Trent Boult",
    role: "Bowler",
    overall: 91,
    batting: 30,
    bowling: 95,
  },
  {
    id: 9,
    name: "Yuzvendra Chahal",
    role: "Bowler",
    overall: 92,
    batting: 25,
    bowling: 97,
  },
  {
    id: 10,
    name: "Avesh Khan",
    role: "Bowler",
    overall: 86,
    batting: 35,
    bowling: 90,
  },
  {
    id: 11,
    name: "Prasidh Krishna",
    role: "Bowler",
    overall: 85,
    batting: 25,
    bowling: 89,
  },
  {
    id: 12,
    name: "Sandeep Sharma",
    role: "Bowler",
    overall: 84,
    batting: 30,
    bowling: 88,
  },
  {
    id: 13,
    name: "Adam Zampa",
    role: "Bowler",
    overall: 88,
    batting: 25,
    bowling: 93,
  },
  {
    id: 14,
    name: "Rovman Powell",
    role: "AR",
    overall: 85,
    batting: 90,
    bowling: 65,
  },
  {
    id: 15,
    name: "Donovan Ferreira",
    role: "WK",
    overall: 80,
    batting: 83,
    bowling: 10,
  },
  {
    id: 16,
    name: "Tom Kohler-Cadmore",
    role: "Batter",
    overall: 81,
    batting: 85,
    bowling: 10,
  },
  {
    id: 17,
    name: "Kuldip Yadav",
    role: "Bowler",
    overall: 78,
    batting: 20,
    bowling: 84,
  },
  {
    id: 18,
    name: "Navdeep Saini",
    role: "Bowler",
    overall: 82,
    batting: 25,
    bowling: 87,
  },
]
  },
  {
    id:15,
    name: "Sunrisers Hyderabad",
    countryCode: "SRH",
    logo:"/srh_logo.jpg",
    players: [
  {
    id: 1,
    name: "Pat Cummins",
    role: "AR",
    overall: 92,
    batting: 65,
    bowling: 95,
  },
  {
    id: 2,
    name: "Travis Head",
    role: "Batter",
    overall: 92,
    batting: 95,
    bowling: 30,
  },
  {
    id: 3,
    name: "Abhishek Sharma",
    role: "AR",
    overall: 88,
    batting: 90,
    bowling: 75,
  },
  {
    id: 4,
    name: "Aiden Markram",
    role: "Batter",
    overall: 89,
    batting: 92,
    bowling: 35,
  },
  {
    id: 5,
    name: "Heinrich Klaasen",
    role: "WK",
    overall: 91,
    batting: 95,
    bowling: 5,
  },
  {
    id: 6,
    name: "Rahul Tripathi",
    role: "Batter",
    overall: 86,
    batting: 89,
    bowling: 15,
  },
  {
    id: 7,
    name: "Nitish Reddy",
    role: "AR",
    overall: 83,
    batting: 85,
    bowling: 70,
  },
  {
    id: 8,
    name: "Marco Jansen",
    role: "AR",
    overall: 87,
    batting: 78,
    bowling: 91,
  },
  {
    id: 9,
    name: "Washington Sundar",
    role: "AR",
    overall: 86,
    batting: 75,
    bowling: 90,
  },
  {
    id: 10,
    name: "Bhuvneshwar Kumar",
    role: "Bowler",
    overall: 88,
    batting: 40,
    bowling: 92,
  },
  {
    id: 11,
    name: "T Natarajan",
    role: "Bowler",
    overall: 89,
    batting: 30,
    bowling: 94,
  },
  {
    id: 12,
    name: "Umran Malik",
    role: "Bowler",
    overall: 86,
    batting: 20,
    bowling: 93,
  },
  {
    id: 13,
    name: "Mayank Markande",
    role: "Bowler",
    overall: 83,
    batting: 25,
    bowling: 88,
  },
  {
    id: 14,
    name: "Glenn Phillips",
    role: "AR",
    overall: 87,
    batting: 90,
    bowling: 70,
  },
  {
    id: 15,
    name: "Anmolpreet Singh",
    role: "Batter",
    overall: 80,
    batting: 84,
    bowling: 10,
  },
  {
    id: 16,
    name: "Upendra Yadav",
    role: "WK",
    overall: 78,
    batting: 82,
    bowling: 5,
  },
  {
    id: 17,
    name: "Fazalhaq Farooqi",
    role: "Bowler",
    overall: 84,
    batting: 20,
    bowling: 90,
  },
  {
    id: 18,
    name: "Jaydev Unadkat",
    role: "Bowler",
    overall: 82,
    batting: 35,
    bowling: 87,
  },
]
  },
  {
    id:16,
    name: "Punjab Kings",
    countryCode: "PBKS",
    logo:"/pbks_logo.jpg",
    players: [
  {
    id: 1,
    name: "Shikhar Dhawan",
    role: "Batter",
    overall: 88,
    batting: 91,
    bowling: 10,
  },
  {
    id: 2,
    name: "Jonny Bairstow",
    role: "WK",
    overall: 90,
    batting: 94,
    bowling: 5,
  },
  {
    id: 3,
    name: "Prabhsimran Singh",
    role: "WK",
    overall: 84,
    batting: 88,
    bowling: 5,
  },
  {
    id: 4,
    name: "Liam Livingstone",
    role: "AR",
    overall: 91,
    batting: 94,
    bowling: 80,
  },
  {
    id: 5,
    name: "Sam Curran",
    role: "AR",
    overall: 90,
    batting: 85,
    bowling: 92,
  },
  {
    id: 6,
    name: "Jitesh Sharma",
    role: "WK",
    overall: 85,
    batting: 89,
    bowling: 5,
  },
  {
    id: 7,
    name: "Shashank Singh",
    role: "AR",
    overall: 82,
    batting: 85,
    bowling: 70,
  },
  {
    id: 8,
    name: "Sikandar Raza",
    role: "AR",
    overall: 87,
    batting: 84,
    bowling: 88,
  },
  {
    id: 9,
    name: "Arshdeep Singh",
    role: "Bowler",
    overall: 89,
    batting: 25,
    bowling: 94,
  },
  {
    id: 10,
    name: "Kagiso Rabada",
    role: "Bowler",
    overall: 92,
    batting: 40,
    bowling: 96,
  },
  {
    id: 11,
    name: "Rahul Chahar",
    role: "Bowler",
    overall: 86,
    batting: 30,
    bowling: 91,
  },
  {
    id: 12,
    name: "Harpreet Brar",
    role: "AR",
    overall: 83,
    batting: 75,
    bowling: 86,
  },
  {
    id: 13,
    name: "Nathan Ellis",
    role: "Bowler",
    overall: 84,
    batting: 30,
    bowling: 89,
  },
  {
    id: 14,
    name: "Rilee Rossouw",
    role: "Batter",
    overall: 86,
    batting: 90,
    bowling: 15,
  },
  {
    id: 15,
    name: "Atharva Taide",
    role: "Batter",
    overall: 80,
    batting: 83,
    bowling: 15,
  },
  {
    id: 16,
    name: "Tanay Thyagarajan",
    role: "Bowler",
    overall: 78,
    batting: 20,
    bowling: 84,
  },
  {
    id: 17,
    name: "Vidwath Kaverappa",
    role: "Bowler",
    overall: 79,
    batting: 20,
    bowling: 86,
  },
  {
    id: 18,
    name: "Chris Woakes",
    role: "AR",
    overall: 88,
    batting: 78,
    bowling: 92,
  },
]
  },
  {
    id:17,
    name: "Delhi Capitals",
    countryCode: "DC",
    logo:"/dc_logo.jpg",
    players: [
  {
    id: 1,
    name: "Rishabh Pant",
    role: "WK",
    overall: 93,
    batting: 96,
    bowling: 5,
  },
  {
    id: 2,
    name: "David Warner",
    role: "Batter",
    overall: 90,
    batting: 93,
    bowling: 10,
  },
  {
    id: 3,
    name: "Prithvi Shaw",
    role: "Batter",
    overall: 85,
    batting: 89,
    bowling: 5,
  },
  {
    id: 4,
    name: "Jake Fraser-McGurk",
    role: "Batter",
    overall: 88,
    batting: 92,
    bowling: 15,
  },
  {
    id: 5,
    name: "Tristan Stubbs",
    role: "AR",
    overall: 86,
    batting: 90,
    bowling: 70,
  },
  {
    id: 6,
    name: "Axar Patel",
    role: "AR",
    overall: 90,
    batting: 82,
    bowling: 92,
  },
  {
    id: 7,
    name: "Mitchell Marsh",
    role: "AR",
    overall: 90,
    batting: 92,
    bowling: 80,
  },
  {
    id: 8,
    name: "Kuldeep Yadav",
    role: "Bowler",
    overall: 91,
    batting: 35,
    bowling: 96,
  },
  {
    id: 9,
    name: "Anrich Nortje",
    role: "Bowler",
    overall: 89,
    batting: 30,
    bowling: 94,
  },
  {
    id: 10,
    name: "Khaleel Ahmed",
    role: "Bowler",
    overall: 85,
    batting: 25,
    bowling: 90,
  },
  {
    id: 11,
    name: "Mukesh Kumar",
    role: "Bowler",
    overall: 83,
    batting: 30,
    bowling: 88,
  },
  {
    id: 12,
    name: "Lalit Yadav",
    role: "AR",
    overall: 82,
    batting: 80,
    bowling: 82,
  },
  {
    id: 13,
    name: "Ricky Bhui",
    role: "Batter",
    overall: 79,
    batting: 83,
    bowling: 10,
  },
  {
    id: 14,
    name: "Kumar Kushagra",
    role: "WK",
    overall: 78,
    batting: 82,
    bowling: 5,
  },
  {
    id: 15,
    name: "Sumit Kumar",
    role: "AR",
    overall: 77,
    batting: 75,
    bowling: 80,
  },
  {
    id: 16,
    name: "Jhye Richardson",
    role: "Bowler",
    overall: 84,
    batting: 30,
    bowling: 90,
  },
  {
    id: 17,
    name: "Ishant Sharma",
    role: "Bowler",
    overall: 83,
    batting: 35,
    bowling: 88,
  },
  {
    id: 18,
    name: "Shai Hope",
    role: "WK",
    overall: 85,
    batting: 88,
    bowling: 5,
  },
]
  },
  {
    id:18,
    name: "Lucknow Super Giants",
    countryCode: "LSG",
    logo:"/lsg_logo.jpg",
    players: [
  {
    id: 1,
    name: "KL Rahul",
    role: "WK",
    overall: 91,
    batting: 94,
    bowling: 5,
  },
  {
    id: 2,
    name: "Quinton de Kock",
    role: "WK",
    overall: 90,
    batting: 93,
    bowling: 5,
  },
  {
    id: 3,
    name: "Nicholas Pooran",
    role: "WK",
    overall: 92,
    batting: 96,
    bowling: 5,
  },
  {
    id: 4,
    name: "Devdutt Padikkal",
    role: "Batter",
    overall: 85,
    batting: 89,
    bowling: 10,
  },
  {
    id: 5,
    name: "Ayush Badoni",
    role: "Batter",
    overall: 83,
    batting: 87,
    bowling: 20,
  },
  {
    id: 6,
    name: "Marcus Stoinis",
    role: "AR",
    overall: 90,
    batting: 92,
    bowling: 82,
  },
  {
    id: 7,
    name: "Krunal Pandya",
    role: "AR",
    overall: 88,
    batting: 80,
    bowling: 90,
  },
  {
    id: 8,
    name: "Kyle Mayers",
    role: "AR",
    overall: 87,
    batting: 90,
    bowling: 75,
  },
  {
    id: 9,
    name: "Ravi Bishnoi",
    role: "Bowler",
    overall: 90,
    batting: 25,
    bowling: 96,
  },
  {
    id: 10,
    name: "Mark Wood",
    role: "Bowler",
    overall: 91,
    batting: 30,
    bowling: 97,
  },
  {
    id: 11,
    name: "Mohsin Khan",
    role: "Bowler",
    overall: 86,
    batting: 25,
    bowling: 91,
  },
  {
    id: 12,
    name: "Naveen-ul-Haq",
    role: "Bowler",
    overall: 88,
    batting: 30,
    bowling: 93,
  },
  {
    id: 13,
    name: "Yash Thakur",
    role: "Bowler",
    overall: 82,
    batting: 25,
    bowling: 88,
  },
  {
    id: 14,
    name: "Deepak Hooda",
    role: "AR",
    overall: 85,
    batting: 88,
    bowling: 72,
  },
  {
    id: 15,
    name: "Ashton Turner",
    role: "Batter",
    overall: 82,
    batting: 86,
    bowling: 15,
  },
  {
    id: 16,
    name: "Arshin Kulkarni",
    role: "AR",
    overall: 79,
    batting: 82,
    bowling: 78,
  },
  {
    id: 17,
    name: "Amit Mishra",
    role: "Bowler",
    overall: 81,
    batting: 30,
    bowling: 87,
  },
  {
    id: 18,
    name: "Matt Henry",
    role: "Bowler",
    overall: 87,
    batting: 35,
    bowling: 92,
  },
]
  },
];


export const getInternationalTeamData = (selectTeam: string) => {
  const teamData = internationalCricketData.find(
    (items) => selectTeam === items.name,
  );
  return teamData;
};

export const getIplTeamData = (selectTeam: string) => {
  const teamData = iplCricketData.find((items) => selectTeam === items.name);
  return teamData;
};
