import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  notification,
  activity,
}: Readonly<{
  children: React.ReactNode;
  notification: React.ReactNode;
  activity: React.ReactNode;
}>) {
  console.log("Parent layout");

  return (
    <html>
      <body className="w-full h-screen border border-green-300">
        <h1>Root layout</h1>
        <div>{children}</div>
        <div>{notification}</div>
        <div>{activity}</div> 
      </body>
    </html>
  );
}
