import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import { StatusProvider } from "./StatusContext";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
  title: "Optimizely Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex h-screen w-full overflow-x-hidden justify-center">
        <Providers>
          <ThemeRegistry>
            <StatusProvider >
              {children}
            </StatusProvider>
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}