import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import { StatusProvider } from "./StatusContext";
import ThemeRegistry from "./ThemeRegistry";
import { LeagueProvider } from "@/Context/LeagueContext";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Optimizely Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className="flex w-full min-h-screen">
        <Providers>
          <LeagueProvider>
            <ThemeRegistry>
              <StatusProvider>{children}</StatusProvider>
                <Toaster />
            </ThemeRegistry>
          </LeagueProvider>
        </Providers>
      </body>
    </html>
  );
}
