import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import { StatusProvider } from "./StatusContext";
import ThemeRegistry from "./ThemeRegistry";
import { LeagueProvider } from "@/Context/LeagueContext";

export const metadata: Metadata = {
  title: "Optimizely Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex w-full min-h-screen overflow-x-hidden">
        <Providers>
          <LeagueProvider>
            <ThemeRegistry>
              <StatusProvider>{children}</StatusProvider>
            </ThemeRegistry>
          </LeagueProvider>
        </Providers>
      </body>
    </html>
  );
}
